#!/usr/bin/env bash
if [[ "$1" = configure ]]; then
    if ! grep -q 'gpio_ir_recv   rc-rc6-mce            allo_boss2_remote.toml' /etc/rc_maps.cfg; then
        echo 'gpio_ir_recv   rc-rc6-mce            allo_boss2_remote.toml' >>/etc/rc_maps.cfg
    fi
fi
