name: Build deb

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Update APT repo
        run: apt-get update

      - name: Install make
        run: apt-get install make -y

      - name: Run build
        run: make build
